[package]
name = "colomar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.6.0"
once_cell = "1.17.0"
# anyhow = "1.0.47"
# peekmore = "1.0.0"
# strum = "0.13.0"
# strum_macros = "0.13.0"