[package]
name = "colomar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2" # Lexer and parser
once_cell = "1.17.0"
ariadne = "0.2.0" # Error reporting
derivative = "2.2.0"
petgraph = "0.6.3" # Remove that
salsa = "0.17.0-pre.2" # Analysis and compiler
# anyhow = "1.0.47"
# peekmore = "1.0.0"
# strum = "0.13.0"
# strum_macros = "0.13.0"