[package]
name = "colomar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["colomar_macros", "compiler"]

[dependencies]
compiler = { path = "compiler" } # compiler