Slot0 = "Slot 0"
Slot1 = "Slot 1"
Slot2 = "Slot 2"
Slot3 = "Slot 3"
Slot4 = "Slot 4"
Slot5 = "Slot 5"
Slot6 = "Slot 6"
Slot7 = "Slot 7"
Slot8 = "Slot 8"
Slot9 = "Slot 9"
Slot10 = "Slot 10"
Slot11 = "Slot 11"