self = "Event Player"

[getval]
hero = "Hero Of(%self%)"
isReloading = "Is Reloading(%self%)"

[setval]
ability1Enabled = "Set Ability 1 Enabled(%self%, %value%)"

[variables]

[functions]
heal = "Heal(%self%, %healer%, %amount%)"
displaySmallMessage = "SmallMessage(%message%)"